In [2]:
import numpy as np, scipy as sp, pandas as pd, sklearn as sk
from sklearn.neighbors import KNeighborsRegressor

In [28]:
def write_policy(dataset, policy):
    file = open(dataset + ".policy", "w")
    
    for i in range(len(policy)):
        state = str(int(policy[i])) +"\n"
        file.write(state)

    file.close()

In [3]:
data = pd.read_csv('small.csv') 

In [5]:
data.head(5)

s  a  r  sp
0  46  4  0  36
1  36  1  0  35
2  35  2  0  34
3  34  1  0  33
4  33  2  0  43

In [7]:
#setup

states, actions = data.s.unique(), data.a.unique()
state_count, action_count = len(states), len(actions)

In [9]:
#computes simple transition matrix

tmat = np.zeros((state_count, action_count, state_count))
rmat = np.zeros((state_count, action_count))

for i in data.values:  
    tmat[i[0]-1, i[1]-1, i[3]-1] += 1
    rmat[i[0]-1, i[1]-1] = i[2]
tmat /= np.sum(tmat, axis=-1, keepdims=True)

In [4]:
def transition_calc(df):
    
    states, actions = data.s.unique(), data.a.unique()
    state_count, action_count = len(states), len(actions)
    
    tmat = np.zeros((state_count, action_count, state_count))
    rmat = np.zeros((state_count, action_count))

    for i in data.values:  
        tmat[i[0]-1, i[1]-1, i[3]-1] += 1
        rmat[i[0]-1, i[1]-1] = i[2]
    tmat /= np.sum(tmat, axis=-1, keepdims=True)
    
    return states, actions, tmat, rmat

## some testing / rationality ##

In [366]:
rmat[:,0]

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  3.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0., 10.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [428]:
#state 1 > action 1, you stay in 1 with 100% probability

s=12
a=3
print(np.where(tmat[s][a] !=0)[0]+1)

tmat[s][a][13]

[ 3 12 14 23]


0.128

In [338]:
#state 12 > action 2, you go to 2/11/13/22 with 10/12/60/16% prob

s=12
a=2

print('possible states: ',np.where(tmat[s][a] !=0)[0]+1)

np.where(tmat[s][a] !=0)[0] #these are the states that are possible
print('rewards',rmat[tmat[s][a] !=0]) #these are the rewards from transitioning
print('probs',tmat[s][a][tmat[s][a] !=0])


tmat[s][a][tmat[s][a] !=0]@rmat[tmat[s][a] !=0][a]

possible states:  [ 3 12 14 23]
rewards [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
probs [0.16  0.152 0.112 0.576]


0.0

In [ ]:
exp_r = tmat[state][action][tmat[state][action] !=0]@rmat[tmat[state][action] !=0][a]

In [270]:
rmat[:,0]

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  3.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0., 10.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [272]:
s0 = np.random.randint(1,100,1)[0]
print(s0)
#tmat[s0][0]

[tmat[s0][i]@rmat[:,0] for i in range(action_count)]
rmat[1,2]

48


0.0

In [408]:
rmat[:,0]

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  3.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0., 10.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [483]:
a = 4
tmat[4][a-1]

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [55]:
np.where(tmat[0][0] !=0)[0]

array([0])

In [130]:
#tmat[0]

## now some iteration ##

In [5]:
def value_iteration(data, iters, discount, verbose):
    
    states, actions, tmat, rmat = transition_calc(data)
    state_count, action_count = len(states), len(actions)
    policy = np.zeros((iters, state_count))
    v = np.zeros(state_count)
        
    for i in range(iters):
        
        v_temp = np.zeros(state_count)
        
        for state in range(state_count):
            rewards = {}
            
            if verbose == True:
                print('\ncurrent state:', state, '\ncurrent value:', v[state])
                print('possible states:', np.where(tmat[state][0] !=0)[0],'\n')
            
            total = 0
            for action in range(action_count):
                exp_r = tmat[state][action]@rmat[:,action]
                possible_actions = np.where(tmat[state][action] != 0)[0]
                next_states = np.sum([v[j]*tmat[state][action][j] for j in possible_actions])
                rewards[action] = exp_r + (discount * next_states)

            if verbose == True:
                print('Actions/Rewards:\n', rewards)
            
            reward_max = max(rewards.values())
            v_temp[state] = reward_max

            best_action = [x==reward_max for x in rewards.values()].index(True)
            policy[i][state] = best_action
            
            if verbose == True:
                print('### Optimal Action: ', best_action,'###\n')

        v = v_temp

        
        if verbose == True:
            print('###############\nvalue update:', v, '\n###############')

    return v, policy[-1]+1

In [144]:
iters = 10
discount = 0.95
verbose = False

value_iteration(data, iters, discount, verbose)

(array([ 2.27043817,  3.54890064,  4.31352015,  6.17923608,  6.86000568,
         5.96863829,  4.2407808 ,  3.4730662 ,  1.91369162,  1.60556239,
         3.10683449,  3.79206374,  5.76486615,  7.30553371,  6.76064231,
         6.98164382,  5.40008943,  3.31202021,  2.52307141,  1.31894177,
         2.87554354,  4.43752686,  4.27633567,  6.08424001,  6.65576667,
         5.88480518,  4.0351088 ,  2.99130568,  1.66987084,  1.31338537,
         5.83516819,  5.60605151,  5.35522388,  4.36391632,  5.2539241 ,
         3.77630101,  3.15842904,  1.78759122,  1.40198971,  0.63994797,
         7.34590057,  9.98710101,  6.24057177,  5.7231051 ,  3.51952618,
         3.10123775,  1.71177601,  1.44088242,  0.66479122,  0.53648669,
        12.81580916, 13.08266707, 10.95122824,  6.78235669,  5.58210949,
         2.6474274 ,  2.16444068,  0.70246329,  0.54213875,  0.12668219,
        15.84642982, 20.16360658, 13.85832866, 11.71546998,  6.82466048,
         5.55571862,  2.34914055,  1.5955486 ,  0.3

In [7]:
iters = 100
discount = 0.95
verbose = False

value_iteration(data, iters, discount, verbose)

(array([28.31422613, 28.23968914, 26.95180892, 26.26946799, 26.41003609,
        24.14212797, 22.20337661, 20.29390764, 18.39522877, 17.26234101,
        30.95758976, 31.05965416, 29.30005601, 28.30854097, 26.62751854,
        26.4522315 , 23.54165574, 21.21850112, 19.26579142, 17.79857052,
        34.41853635, 34.80557964, 32.35807425, 30.6559104 , 28.5351844 ,
        26.45274569, 24.2341858 , 21.95880005, 20.16725075, 18.70951875,
        38.21235316, 39.43783157, 36.26672151, 34.09442775, 30.96191074,
        28.48052177, 25.73183097, 23.4327951 , 21.39531522, 19.81516874,
        42.29387382, 43.54369321, 40.31141427, 37.49841957, 33.99490719,
        31.13943772, 28.1238132 , 25.48459243, 23.32614654, 21.32676038,
        47.00817347, 49.02785126, 44.6647214 , 41.33706458, 37.65911318,
        34.28884828, 31.12563267, 27.93351223, 25.26089145, 23.18334778,
        52.2319974 , 54.80332523, 49.87756978, 45.70316272, 41.58556678,
        37.94417252, 34.09232509, 30.20765464, 27.3

In [1]:
iters = 1000
discount = 0.95
verbose = False

value_iteration(data, iters, discount, verbose)

NameError: name 'value_iteration' is not defined

In [6]:
iters = 10000
discount = 0.95
verbose = False

value, policy = value_iteration(states, actions, rmat, tmat, iters, discount, verbose)

NameError: name 'states' is not defined

In [66]:
write_policy('small', policy)

In [65]:
policy.reshape(10,10)

array([[3., 3., 3., 3., 3., 3., 1., 1., 1., 1.],
       [3., 3., 3., 3., 3., 1., 1., 1., 1., 1.],
       [3., 3., 3., 3., 3., 3., 1., 1., 1., 1.],
       [3., 3., 3., 3., 1., 3., 3., 1., 3., 1.],
       [3., 3., 3., 3., 1., 3., 3., 1., 1., 3.],
       [3., 3., 3., 3., 3., 1., 1., 1., 1., 1.],
       [2., 3., 3., 3., 3., 3., 1., 1., 3., 1.],
       [3., 3., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [4., 4., 4., 1., 1., 1., 1., 1., 1., 1.]])

## medium ##

create full Q table using KNN/regression/etc.

try Q learning

try sarsa learning

this basically needs to be done when you hit the 10,000 reward

In [145]:
data = pd.read_csv('medium.csv') 

In [87]:
data.head(10)

s  a   r     sp
0  24705  3 -25  24705
1  24705  3 -25  24704
2  24704  3 -25  24204
3  24204  3 -25  24203
4  24203  3 -25  24203
5  24203  3 -25  23702
6  23702  3 -25  23701
7  23701  3 -25  23700
8  23700  3 -25  23699
9  23699  3 -25  23698

In [98]:
knn = KNeighborsRegressor(n_neighbors=20)
knn.fit(data[data.columns[0:2]], data.r)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=20, p=2,
                    weights='uniform')

In [127]:
np.max([[knn.predict([[j, i]]) for i in range(7)] for j in range(200,4000)])

-72.5

In [104]:
np.min(data.s)

657

In [113]:
np.max(data.s)

49252

In [122]:
data.describe()

s              a             r             sp
count  100000.000000  100000.000000  100000.00000  100000.000000
mean    25690.109410       4.031410     127.76475   25715.274830
std      8278.337595       1.780015    4544.73829    8302.383438
min       657.000000       1.000000    -225.00000     657.000000
25%     21683.000000       3.000000    -100.00000   21682.000000
50%     25196.000000       4.000000     -25.00000   25195.000000
75%     29703.000000       5.000000     -25.00000   29720.000000
max     49252.000000       7.000000  100000.00000   49252.000000

In [164]:
s = 49252
a = 8
query = 's == '+ str(s) +' and a == '+ str(a)
len(data.query(query))

0

In [161]:
Q = np.zeros((50000,7))
Q

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [162]:
state_count = 50000
action_count = 7

In [ ]:
#try to inference about other state/value pairs

for i in range(state_count):
    for j in range(action_count):
        query = 's == '+ str(i) +' and a == '+ str(j)
        if len(data.query(query)) == 0:
            [knn.predict([[i, j]])